#ifndef _TYPES_H
#define _TYPES_H

namespace minecraftpp {

const uint32_t MEGABYTE = 1024*1024;
const uint16_t SECTOR_SIZE = 4096;

const uint8_t CHUNKX = 16;
const uint8_t CHUNKY = 128;
const uint8_t CHUNKZ = 16;

const uint8_t REGIONX = 32;
const uint8_t REGIONZ = 32;

//Chunk File String Constants
const std::string LEVEL = "Level";
const std::string BLOCKS = "Blocks";
const std::string BLOCK_DATA = "Data";
const std::string SKY_LIGHT = "SkyLight";
const std::string BLOCK_LIGHT = "BlockLight";
const std::string HEIGHT_MAP = "HeightMap";
const std::string ENTITIES = "Entities";
const std::string TILE_ENTITIES = "TileEntities";
const std::string LAST_UPDATE ="LastUpdate";
const std::string X_POS = "xPos";
const std::string Z_POS = "zPos";
const std::string TERRAIN_POPULATED = "TerrainPopulated";


enum BlockType {
	BLOCK_AIR, /* 0 */
	BLOCK_STONE,
	BLOCK_GRASS,
	BLOCK_DIRT,
	BLOCK_COBBLESTONE,
	BLOCK_PLANK,
	BLOCK_SAPLING,
	BLOCK_BEDROCK,
	BLOCK_WATER,
	BLOCK_STATIONARY_WATER,
	BLOCK_LAVA, /* 10 */
	BLOCK_STATIONARY_LAVA,
	BLOCK_SAND,
	BLOCK_GRAVEL,
	BLOCK_GOLD_ORE,
	BLOCK_IRON_ORE,
	BLOCK_COAL_ORE,
	BLOCK_WOOD,
	BLOCK_LEAVES,
	BLOCK_SPONGE,
	BLOCK_GLASS, /* 20 */
	BLOCK_LAPIS_ORE,
	BLOCK_LAPIS_BLOCK,
	BLOCK_DISPENSER,
	BLOCK_SANDSTONE,
	BLOCK_NOTE_BLOCK,
	BLOCK_BED, /* 26 */
	BLOCK_WOOL = 35,
	BLOCK_YELLOW_FLOWER = 37,
	BLOCK_ROSE,
	BLOCK_BROWN_MUSHROOM,
	BLOCK_RED_MUSHROOM, /* 40 */
	BLOCK_GOLD_BLOCK,
	BLOCK_IRON_BLOCK,
	BLOCK_DOUBLE_SLAB,
	BLOCK_SLAB,
	BLOCK_BRICK_BLOCK,
	BLOCK_TNT,
	BLOCK_BOOKSHELF,
	BLOCK_MOSSY_COBBLESTONE,
	BLOCK_OBSIDIAN,
	BLOCK_TORCH, /* 50 */
	BLOCK_FIRE,
	BLOCK_SPAWNER,
	BLOCK_WOODEN_STAIRS,
	BLOCK_CHEST,
	BLOCK_REDSTONE_WIRE,
	BLOCK_DIAMOND_ORE,
	BLOCK_DIAMOND_BLOCK,
	BLOCK_CRAFTING_TABLE,
	BLOCK_CROPS,
	BLOCK_FARMLAND, /* 60 */
	BLOCK_FURNACE,
	BLOCK_BURNING_FURNACE,
	BLOCK_SIGN_POST,
	BLOCK_WOODEN_DOOR,
	BLOCK_LADDER,
	BLOCK_RAILS,
	BLOCK_COBBLESTONE_STAIRS,
	BLOCK_WALL_SIGN,
	BLOCK_LEVER,
	BLOCK_STONE_PRESSURE_PLATE, /* 70 */
	BLOCK_IRON_DOOR,
	BLOCK_WOODEN_PRESSURE_PLATE,
	BLOCK_REDSTONE_ORE,
	BLOCK_GLOWING_REDSTONE_ORE,
	BLOCK_REDSTONE_TORCH_OFF,
	BLOCK_REDSTONE_TORCH_ON,
	BLOCK_STONE_BUTTON,
	BLOCK_SNOW,
	BLOCK_ICE,
	BLOCK_SNOW_BLOCK, /* 80 */
	BLOCK_CACTUS,
	BLOCK_CLAY_BLOCK,
	BLOCK_SUGAR_CANE,
	BLOCK_JUKEBOX,
	BLOCK_FENCE,
	BLOCK_PUMPKIN,
	BLOCK_NETHERRACK,
	BLOCK_SOUL_SAND,
	BLOCK_GLOWSTONE_BLOCK,
	BLOCK_PORTAL, /* 90 */
	BLOCK_JACKOLANTERN,
	BLOCK_CAKE,
	BLOCK_REDSTONE_REPEATER_OFF,
	BLOCK_REDSTONE_REPEATER_ON
};

enum WoolColour {
	WHITE,
	ORANGE,
	MAGENTA,
	LIGHT_BLUE,
	YELLOW,
	LIGHT_GREEN,
	PINK,
	GRAY,
	LIGHT_GRAY,
	CYAN,
	PURPLE,
	BLUE,
	BROWN,
	DARK_GREEN,
	RED,
	BLACK
};

}
#endif
